### PR TITLE
Add French language

### LINKED ISSUE #203: Add French language
The idea is by @Ilithy

### PR DESCRIPTION
**Pull request by Ilithy**
Resolves #203

### CODE REVIEW

**Comment by nivisi** [comment]
@Ilithy as you can see, the CI failed. There's something with formatting:
> Formatted lib/resources/localization/l10n_provider_map_fr_fr.dart
Formatted 231 files (1 changed) in 1.18 seconds.

Can you check it out? Most likely you need to press Command (Ctlr) + S or run `flutter format .` in the terminal. Then push the needed change.

**Comment by Ilithy** [comment]
I'm in uncharted territory, I only have my smartphone, and I have no way to check where the error is, I'm really sorry, I looked at the file quoted, I do not find any error ... since it is not good, I close this PR.
:-/

**Comment by nivisi** [comment]
@Ilithy you've made this PR with a smartphone? 😳

If you'd clone the repo instead of forking and provide these changes within the cloned repo, I could finish it for ya.

**Comment by Ilithy** [comment]
@nivisi indeed, I run everything from my pixel 6 pro, it's not the most practical.

sorry, but I can't find the changes to make, and not being a coder, I'm totally lost.

I don't want to disturb you, and make you lose more time unnecessarily, so I stopped the PR.  1-1

**Comment by nivisi** [comment]
@Ilithy I'll take the map you provided and will introduce French to Leafy so your work won't be lost. Thanks!

**Comment by Ilithy** [comment]
I may have found my mistake.

I forgot to add between line 113 and 116 this element:
`L10n.frlocal,`


in the file (/src/lib/applications/launcher/)leafy_launcher.dart

**Pull request closed without merging**
